config/routes.rb
Rails.application.routes.draw do
  resources :sessions
  get 'login', to: 'sessions#new', as: 'login'
  delete 'logout', to: 'sessions#destroy', as: 'logout'
  resources :users
  root 'users#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  has_one_attached :avatar
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user
  helper_method :logged_in?
  helper_method :logged_in_user

  def current_user
    User.find_by(id: session[:user_id])
  end

  def logged_in?
    !current_user.nil?
  end

  def logged_in_user
    unless logged_in?
      redirect_to root_path
      flash[:danger] = "Please Log In or Sign Up."
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    @user = User.find_by(username: params[:username])
    if @user && @user.authenticate(params[:password])
      session[:user_id] = @user.id
      redirect_to edit_user_path(@user), notice: 'Logged In'
    else
      redirect_to '/login'
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path, notice: 'Logged Out!'
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_action :logged_in_user, only: [:edit, :update, :show, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end
  # <%= link_to "Logout", logout_path, method: :delete, class:"text-info" %>
  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def user_params
      params.require(:user).permit(:username, :password, :avatar)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PalmasMenu</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :username %>
    <%= form.text_field :username %>
  </div>

  <div class="field">
    <%= form.label :password %>
    <%= form.text_field :password %>
  </div>

  <div class="field">
    <%= form.label :menu_photos %>
    <%= form.file_field :avatar %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/users/_form_edit.html.erb
<%= form_with(model: user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field text-center mt-3 d-flex flex-column align-items-center justify-content-center">
    <%= form.label :elige_la_foto %>
    <%= form.file_field :avatar %>
  </div>

  <div class="actions mt-3">
    <%= form.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<div class="container-fluid d-flex align-items-center flex-column justify-content-center text-center mt-5">
<h3 class="text-info text-uppercase">Cambiar el menú</h3>
<h5 class="text-success text-uppercase">Change menu</h5>

<%= render 'form_edit', user: @user %>

<br>
<%= link_to "cancelar", logout_path, method: :delete, class:"text-info mt-5 text-uppercase" %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<div class="container-fluid">
  <div class="row align-text-center">
    <div class="col-12 text-center">
      <h1 class="text-info">Bienvenido a Las Palmas, Cozumel</h1>
    </div>
    <div class="col-12 text-center">
      <h2>Welcome to Las Palmas, Cozumel</h2>
    </div>
  </div>
</div>
<% @users.each do |user|%>
  <% if user.avatar.attached? %>
    <div class="container-fluid">
      <img src="<%=(url_for(user.avatar))%>" class="image">
    </div>
  <% end %>
<% end %>

<br>
<div class="d-flex flex-column align-items-center mb-5">
  <%= link_to 'cambiar menú', login_path , class: 'link text-uppercase anchor_b' %>
<br>
</div>

<% if false %>
<div class="d-flex flex-column align-items-center mb-5">
  <%= link_to 'Registrar Usuario', new_user_path, class: 'link text-uppercase anchor_a' %>
<br>
</div>
<% end %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<div class="container-fluid d-flex flex-column align-items-center">
<p id="notice" class="text-uppercase"><%= notice %></p>

<h3 class="text-info mt-3 mb-3 anchor">Este el nuevo menú</h3>
<h5 class="text-success mb-5 anchor_a">This is the new menu</h5>

<% if @user.avatar.attached? %>
  <img src="<%=(url_for(@user.avatar))%>">
<% end %>

  <div class="mt-5 mb-5 text-center">
    <%= link_to "CONFIRMAR MENÚ", logout_path, method: :delete, class:"text-info anchor anchor_a" %><br>
    <%= link_to 'regresar y cambiar de menú', edit_user_path(@user), class:"text-danger anchor_a" %>
  </div>
</div>